[tool.poetry]
name = "pyhuum"
version = "0.1.0"
description = "Python library for Huum saunas"
authors = ["Frank Wickstroem <frwickst@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.26.0"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
mypy = "^0.910"
flake8 = "^3.9.2"
types-requests = "^2.25.6"
isort = "^5.9.3"
pytest = "^6.2.5"
pytest-cov = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.coverage.run]
source = ["huum", "tests"]

[tool.coverage.report]
show_missing = true
fail_under = 100
